### ISSUE TITLE
You have lost

### ISSUE THREAD

**Issue by ildar** [stastnypremysl/Mines3D#15]
All the time. Does everybody experience that?

**Comment by stastnypremysl** [comment]
It is the part of the game. "You have lost" part should frustrate you enough, so you will want to win really hard.

**Comment by ildar** [comment]
the behavior changed a lot since the issue was opened. Now it's better:
more fair.

**Comment by stastnypremysl** [comment]
Glad to hear that. :-)

**Comment by ildar** [comment]
now I know what's wrong with it. It says "You have lost" but doesn't show
the mine I was wrong with.
It shows something for a fraction of a second and I see there wasn't any
mine there. Which is disappointing ))
