### ISSUE TITLE
Improve the README.md file for the application download section

### ISSUE THREAD

**Issue by ZineeEddine** [stastnypremysl/Mines3D#18]
Hi, Good job on the project 😎 👍

Maybe someone try improving the README.md file in the section with the links to download the application.

With Google Play Store and F-Droid badges

Here is an example that can be done, which exists on the majority of Mobile Development projects on Github.

<img width="743" alt="Custom_readme" src="https://github.com/stastnypremysl/Mines3D/assets/92603736/5eb44070-d86f-4460-86d9-9c8947363482">

**Comment by stastnypremysl** [comment]
Hello.

Thank you for your suggestion. I changed the README.md file as you proposed.

Best regards
Přemysl
