### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [stastnypremysl/Mines3D#6]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by TranslucentSabre** [comment]
I took a quick look at this, as I am happy to contribute screenshots, and I'm a little confused.
I've not familiar with the F-Droid repository setup, but the metadata link on the [app's page](https://f-droid.org/en/packages/cos.premy.mines/) points to what looks like the [fdroiddata repo](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/cos.premy.mines.yml).

From the "All_About_Descriptions_Graphics_and_Screenshots" linked above, it specifically says that images may not be included with metadata in the fdroiddata repo. Is there another method that is preferred for screenshots?
I can send a PR to add screenshots to the repo in the [Fastlane stucture](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure), but I'm not sure if that will conflict with the metadata already provided.
